### ISSUE TITLE
最新版本微信，canvas无法绘制任何内容

### ISSUE THREAD

**Issue by guoman** [LuckDraw/mini-luck-draw#12]
在最新版本微信上，无法绘制出任何内容出来，包括你官方演示小程序也有这个问题！

**Comment by guoman** [comment]
安卓，IOS，PC微信端，都无法绘制任何内容

**Comment by buuing** [comment]
> 安卓，IOS，PC微信端，都无法绘制任何内容

PC端微信一直都无法绘制, 我这边安卓试了一下`8.0.6`版本canvas绘制正常, 你微信什么版本

**Comment by guoman** [comment]
不好意思，我的失误，只是无法真机调试

**Comment by buuing** [comment]
> 不好意思，我的失误，只是无法真机调试

哦, 那个真机调试有问题, 直接看体验版

**Comment by guoman** [comment]
非常感谢！

**Comment by buuing** [comment]
> 非常感谢！

没事, 使用上有问题可以随时反馈
