### ISSUE TITLE
还没有小程序版的吗

### ISSUE THREAD

**Issue by yigenivhegn** [LuckDraw/mini-luck-draw#3]
- 版本号：

- 平台信息：

- 详细描述：

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
微信小程序原生组件`mini-luck-draw@0.0.4`测试版已发布, 目前已完成机会绘制 (除了渲染图片)

**Comment by buuing** [comment]
`mini-luck-draw@0.0.7`已发布, 增加了图片渲染(网络图片 / base64图片)相关功能
