### ISSUE TITLE
九宫格小程序抽奖按钮 不显示呀

### ISSUE THREAD

**Issue by shenl-ui** [LuckDraw/mini-luck-draw#5]
你好 9宫格的 抽奖按钮 不显示是小程序还没正式发版吗

**Comment by buuing** [comment]
不会啊, 这个早就是正式版了, 你用的什么版本

**Comment by shenl-ui** [comment]
用的是0.0.7 最新版本 我把你们示例的代码全贴过来 就单独的按钮显示不出来

**Comment by buuing** [comment]
额, 最新版是`v1.0.3`, 你升级一下`npm i mini-luck-draw@1.0.3`

**Comment by shenl-ui** [comment]
好 我试一下

**Comment by buuing** [comment]
行, 用着顺手可以点个`star`支持一下😀

**Comment by shenl-ui** [comment]
古德古德 困扰我了一中午 三克油
