### ISSUE TITLE
微信小程序按照您的步骤安装执行

### ISSUE THREAD

**Issue by wanwanyu520** [LuckDraw/mini-luck-draw#6]
参照这个链接写的https://100px.net/usage/wx.html，急用，盼尽快回复，谢谢
![微信图片_20210224110934](https://user-images.githubusercontent.com/30098007/108941911-eb4d1e00-7690-11eb-9cfa-4c36e30a3fd7.png)

**Comment by buuing** [comment]
用的哪个版本啊

**Comment by buuing** [comment]
稍等, 我在看

**Comment by wanwanyu520** [comment]
这个版本，有微信吗，可以微信聊吗








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/mini-luck-draw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 中午11:12
收件人:&nbsp;"LuckDraw/mini-luck-draw"<mini-luck-draw@noreply.github.com&gt;;
抄送:&nbsp;"弯弯鱼"<364842455@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckDraw/mini-luck-draw] 微信小程序按照您的步骤安装执行 (#6)





 
用的哪个版本啊

**Comment by wanwanyu520** [comment]
好的，希望提供一个抽奖按照，转盘，奖品图片，图片名称可以修改的小程序，万分感谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/mini-luck-draw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 中午11:18
收件人:&nbsp;"LuckDraw/mini-luck-draw"<mini-luck-draw@noreply.github.com&gt;;
抄送:&nbsp;"弯弯鱼"<364842455@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckDraw/mini-luck-draw] 微信小程序按照您的步骤安装执行 (#6)





 
稍等, 我在看

**Comment by buuing** [comment]
> 好的，希望提供一个抽奖按照，转盘，奖品图片，图片名称可以修改的小程序，万分感谢

我的微信: `new_ldq`, 目前你可以先安装上一个版本`v1.0.3`

**Comment by buuing** [comment]
最新版已修复该问题
