### ISSUE TITLE
组件引用后会影响page的高度,page下面会多一屏高度的空白

### ISSUE THREAD

**Issue by lyc-123** [LuckDraw/mini-luck-draw#7]

**Comment by buuing** [comment]
我试试

**Comment by buuing** [comment]
我这里挺好的啊...

**Comment by lyc-123** [comment]
就官方的demo也有这个情况

**Comment by buuing** [comment]
![gh_9a65c76818dc_258 (1)](https://user-images.githubusercontent.com/36689704/108974597-92957980-76c0-11eb-81ee-9dc2c4c830f1.jpg)

你是说这个demo吗

**Comment by lyc-123** [comment]
![6851614156739_ pic_hd](https://user-images.githubusercontent.com/30492418/108974725-b1940b80-76c0-11eb-9a28-bf7685d5216e.jpg)
对

**Comment by buuing** [comment]
....奇怪, 我这里没事, 你是什么型号

**Comment by lyc-123** [comment]
我这里用测试机试都有问题  我换个开发工具版本试试, 我这个太新了,别万一是工具问题

**Comment by buuing** [comment]
你试试限制一下高度加个`overflow: hidden`呢?

**Comment by lyc-123** [comment]
试了  其他都没问题,就网易游戏那个会出现      用的是npm下的  "mini-luck-draw": "^1.0.3"这个版本

**Comment by buuing** [comment]
我今天更新了`v1.0.6`, 你也顺便升级一下吧😋

**Comment by lyc-123** [comment]
嗯 限制高度可以暂时解决

**Comment by buuing** [comment]
好的, 那我在下个版本上也在组件内限制一下高度

**Comment by buuing** [comment]
我这里也复现了, 网易云游戏那个demo出现了高度异常, 我研究一下

**Comment by buuing** [comment]
感谢反馈, 最新版`v1.0.7`已修复该问题, 如果用着顺手可以点个`star`支持一下
